services:
  db:
    image: postgres:latest
    container_name: book_market_container
    restart: always
    environment:
      POSTGRES_USER: pinaki
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: book_market_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
