spring.application.name=bookmarkit

spring.datasource.url=jdbc:postgresql://localhost:5432/book_market_db
spring.datasource.username=pinaki
spring.datasource.password=changemeinprod!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=none

google.books.api.key=AIzaSyB8yWAR5EJoaQ5JMSy6O6Ce3YC_nD3IxQg

spring.security.user.password=user
